### ISSUE TITLE
Plans on integrating Matomo's Formanalytics capabilities? 

### ISSUE THREAD

**Issue by TobiGe** [Amsterdam/matomo-tracker#123]
Hi there, 

thanks for providing such a convenient wrapper for tracking React-SPAs. 
We are currently trying to figure out how to make us of matomo's form analytics to capture insights on how our forms are used. 

As far as I could tell, the react-tracker package doesn't support Matomo's form analytics APIs yet, is that correct? If so, are there any future plans to integrate these so that they can be called from the useMatomo hook? 

Best regards,

**Comment by chrisvanmook** [comment]
Hi @TobiGe 

As far as I know Matomo Form Analytics is a (paid) addon, right? We are currently not planning to support this (or other addons) yet. I think it shouldn't be difficult to implement this, though. The `window._paq` object is set, so theoretically you can access Matomo addon api's as they probably extend `_paq`, but I'm not completely sure, I couldn't find documentation about this addon...

**Comment by chrisvanmook** [comment]
@TobiGe Could I help you? Is this issue still relevant?
