### ISSUE TITLE
Integration with React Typescript

### ISSUE THREAD

**Issue by Lawrence23** [Amsterdam/matomo-tracker#137]
Is there a @types package available for this? I am using React with Typescript for my project. It is failing during build because of the absence of .ts/.tsx files for this plugin

**Comment by chrisvanmook** [comment]
Well, the packages we publish already contain the type definition files, as this project in written in typescript. So no **@types** package should be needed! Are you loading the matomo-tracker package? are you using npm / yarn?

**Comment by chrisvanmook** [comment]
@Lawrence23 is this issue still relevant?

**Comment by jonkoops** [comment]
Closing this issue due to unresponsiveness. As mentioned the types should be included in the package itself, if there are any issues regarding the types please make a new issue.
