### ISSUE TITLE
TrackEvents on DOM changes using a MutationObserver

### ISSUE THREAD

**Issue by geier1993** [Amsterdam/matomo-tracker#160]
Problem:
We have a project using React and Elm. The enableLinkTracking function for React just works nice.
But for ELM (external) Javascript this doesn't work out of the Box.
Reviewing the MatomoTracker Code I just found the [trackEvents()](https://github.com/Amsterdam/matomo-tracker/blob/48b33df07fc6bdfac1ad50be8370dd7314831dcb/packages/js/src/MatomoTracker.ts#L82) Method that is querying the DOM for data-matomo-event attributes.
However, for a reactive App we can not make use of this function as the DOM is not static.
But we like the approach to simply add a custom attribute to enable event clicking.

Solution:
To support custom attributes (data-matomo-event) on a frequently changing DOM, I think using a
MutationObserver would be a good solution dynamically add a Click-eventHandler on elements featuring a data-matomo-event attribute.

What do you think?
Are there alternatives I've missed?

**Comment by chrisvanmook** [comment]
@geier1993 Thanks! looking good, left a review :)

**Comment by geier1993** [comment]
Okay thanks! Should be fine now.

When are you publishing to npm the next time? Just have to decide tomorrow whether I just scrap everything I need or to rely on this package

**Comment by chrisvanmook** [comment]
@geier1993 I will publish to npm tomorrow, when this is merged
