### ISSUE TITLE
Cookies timeout / European laws

### ISSUE THREAD

**Issue by MaximilienMeyer** [Amsterdam/matomo-tracker#175]
Hello here, 

I am using this lib in a project, that is under the European laws.
These laws are regulated by an organism, the CNIL, which recommend to delete users cookies after a maximum period of 13 months.

I have found some documentation here : https://www.it-connect.fr/chapitres/matomo-et-la-conformite-cnil-rgpd/ that could allow to do it with basic integration code.

My question is : would it be possible to implement a similar function in this lib ?

**Comment by fcandi** [comment]
Yes, I have the same problem. I need to completely switch off cookies.
