### ISSUE TITLE
React matomo tracker does not track my React App on IE 11.

### ISSUE THREAD

**Issue by sjw441500** [Amsterdam/matomo-tracker#177]
**Describe the bug**
React matomo tracker does not track my React App on IE 11.
it works well on other browsers.
**Expected behavior**
when I click anything on my React site using IE 11,I'm supposed to see the corresponding tracking record on my matomo site.
**Desktop (please complete the following information):**
 - OS: [WINDOWS 10]
 - Browser [IE 11]

**Comment by chrisvanmook** [comment]
Thanks @sjw441500 , we are going to look into this!

**Comment by sjw441500** [comment]
Thanks a lot for help @chrisvanmook,the issue is fixed,I disabled the DoNotTrack in  IE and solve some cookie issue,it works on IE now.Gonna to close this issue.
