### ISSUE TITLE
trackGoal Matomo feature - Manually trigger goal conversions

### ISSUE THREAD

**Issue by gianpo86** [Amsterdam/matomo-tracker#182]
**Is your feature request related to a problem? Please describe.**
It would be awesome to be able to use the trackGoal method of matomo with the javascript tracker

**Describe the solution you'd like**
afaik, matomo supports the manually trigger goal conversions via the trackGoal keyword. 
By default, Goals in Matomo are defined as "matching" parts of the URL (starts with, contains, or regular expression matching). 
I do not know if there is a method that can mimic this in the library, but it would be very helpful, mostly for SPAs without routing, where one cannot use the matomo track goal utilities

**Comment by chrisvanmook** [comment]
@gianpo86 This will be available soon, as you can use a generic method to push instructions to Matomo, as you would to that with `window._paq`

**Comment by jonkoops** [comment]
This has been fixed in #185, will be included in the next version.
