### ISSUE TITLE
matomo-tracker-js, bundle.min.js - not found

### ISSUE THREAD

**Issue by remizovvv** [Amsterdam/matomo-tracker#252]
**Describe the bug**
matomo-tracker-js, bundle.min.js - not found.

Hello, In release v0.2.0, was dropped auto build bundle.min.js file for matomo-tracker-js. How can I build this file without fork all repository and build js part through common package.json ?

**Comment by jonkoops** [comment]
Hi @remizovvv. We have dropped the minified static script from the build since we want to offer our library only through NPM. Could you elaborate on why you need the static file instead of using the existing NPM version?

**Comment by remizovvv** [comment]
Hi @jonkoops. We try optimising our project (we use next.js) for PageSpeed. Server Side Render only, and full disabled hydratation on client side. And we add a little bit client js code (inject as inline scripts). And for work with matomo events, we import and inject bundle.min.js from node_modules. In alternative, I will be mast try add alternative webpack entry point (this default bulder for next.js), special for matomo (but this is a dubious variant). Or I will  be try add special command for build your bundle.min.js before main build our project. And I will be hope, that this my builder don't crash after next release matomo-trackker-js.
I agree, this very rare and specific case, but... may be someone else need this bundle.min, too.

**Comment by jonkoops** [comment]
@remizovvv Good to know what the use case is. We're not looking to bundle any minified version so I would recommend to compile one separately. That said, since this library depends on the Matomo JavaScript client it might be more useful in your case to just load that one in and push instructions there directly.
