### ISSUE TITLE
trackPageView useEffect is re-triggered all the time, following useEffect best practices

### ISSUE THREAD

**Issue by alicerocheman** [Amsterdam/matomo-tracker#253]
**Describe the bug**
trackPageView is re-triggered all the time, following useEffect best practices

**To Reproduce**
```jsx
useEffect(() => {
    console.log('track page view');
    trackPageView();
}, [trackPageView]); // adding trackPageView dependency, according to React Hooks best practices
```
Visit the page once => triggers multiple "track page view" console.logs & matomo events 

**Expected behavior**
Triggers 1 "track page view" console.log & matomo event for 1 visit

**Additional context**
- React ^16.8.0
- React-Router ^5.1.2
- Matomo-Tracker-React ^0.2.1

**Comment by Ditso6** [comment]
fixed by https://github.com/Amsterdam/matomo-tracker/pull/316 and release 0.3.0
