### ISSUE TITLE
trackEvent dependency triggers re-evaluation of hook all the time

### ISSUE THREAD

**Issue by alicerocheman** [Amsterdam/matomo-tracker#254]
**Describe the bug**
When trackEvent is added to a hook's dependencies, the hook is re-evaluated at each render

**To Reproduce**
```jsx
  useEffect(() => {
    console.log('track event');
  }, [trackEvent]);
```
will log "track event" all the time

**Expected behavior**
trackEvent (as well as trackPageView) should only be set at first render, and console.log should only happen once.

**Additional context**
This current behavior means that when using trackEvent in a useCallback, adding trackEvent to dependencies (as should be done according to React Hooks best practices) as such:
```jsx
  const handleClick = useCallback(() => {
    trackEvent({category: "my-page", value:"button-click"});
    doSomething();
  }, [trackEvent, doSomething]);
```
=> the "handleClick" callback will be reset all the time because of the trackEvent dependency, instead of just being evaluated when needed aka when a dependency changes.

**Comment by jonkoops** [comment]
I feel like the problem here is possibly that we need to cache our methods in the hook in a `useMemo()`, for example:

```ts
const trackEvent = (params: TrackEventParams) => instance.trackEvent && instance.trackEvent(params)
```
Would become:

```ts
const trackEvent = useMemo(() => (params: TrackEventParams) => instance.trackEvent && instance.trackEvent(params), [instance.trackEvent])
```
