### ISSUE TITLE
TypeError: pushInstruction is not a function

### ISSUE THREAD

**Issue by brianshano** [Amsterdam/matomo-tracker#370]
**Describe the bug**
I'm trying to push the UserId up to matomo

**To Reproduce**
In react functional component
 ```
 const { pushInstruction } = useMatomo();

useEffect(() => {
    pushInstruction('setUserId', userHome);
  }, [userHome])
```

I want to push the userID up similar to what I do with tracking but it's not working. 
I don't see pushInstruction referenced in matomo-tracker-js/lib/useMatomo.d.ts/ like the other functions (trackPageView, trackLink etc.)

**Unhandled Runtime Error
TypeError: pushInstruction is not a function**

**Comment by jonkoops** [comment]
@brianshano which versions of  `matomo-tracker-react` and `matomo-tracker-js` are you using?

**Comment by brianshano** [comment]
@jonkoops Yes sorry, I was on an old version - 0.1.5
I see it arrived only in 0.2.0 - Upgrading now. 
Thank you!

**Comment by brianshano** [comment]
> @brianshano which versions of `matomo-tracker-react` and `matomo-tracker-js` are you using?

@jonkoops Yes sorry, I was on an old version - 0.1.5
I see it arrived only in 0.2.0 - Upgrading now.
Thank you!
