### ISSUE TITLE
React peer dependencies

### ISSUE THREAD

**Issue by fanick-ber** [Amsterdam/matomo-tracker#4]
Hello,
Thanks for the effort with these very fresh packages!

I just installed in on my react app and faced problems, that the react dependencies are not peerDependencies/devDependencies. Therefore it installed a second react version since I used react 16.8.6. 

Unfortunatly I have only been able to develop locally by changing a lot of the lerna things (I have no experience with lerna unfortunately). Therefore I was not able yet to provide a PR.

Best regards,
Fabian.

**Comment by chrisvanmook** [comment]
Hi @fanick-ber, could you checkout [this PR](https://github.com/Amsterdam/matomo-tracker/pull/6), and see if it would solve your problem?

**Comment by fanick-ber** [comment]
Hi, thanks a lot! 
I have not been available the last couple of days, but I will test the newly published version soon.

**Comment by fanick-ber** [comment]
I can confirm that it works flawless now, also with a different react version installed!
Thanks for the changes!
