### ISSUE TITLE
Support react native or remove the keyword from the package.json

### ISSUE THREAD

**Issue by johannesfritsch** [Amsterdam/matomo-tracker#447]
**Is your feature request related to a problem? Please describe.**
Just spent half an hour adding your module just to find out it requires a global document. So no react native support even though the package.json specifies "react native" as a keyword.

**Describe the solution you'd like**
Either support react native, add documentation on how to get it running on RN or remove the keyword in package.json.

**Describe alternatives you've considered**
- see above -

Thanks :-)

**Comment by jonkoops** [comment]
Good catch, fixed in a3252f89380b44c90e66cb6df5449719d17d5a42.
