### ISSUE TITLE
Support for Angular

### ISSUE THREAD

**Issue by electrofLy** [Amsterdam/matomo-tracker#486]
**Is your feature request related to a problem? Please describe.**

N/A

**Describe the solution you'd like**

Support for Angular.

**Describe alternatives you've considered**

N/A

**Additional context**

Currently, there is no up to date Matomo implementation for Angular. Would you consider adding such to this repository as the setup seems convenient?

**Comment by jonkoops** [comment]
What is preventing you to use this in Angular right now? You'd probably want to set up an [injection token](https://angular.io/guide/dependency-injection-in-action#supply-a-custom-provider-with-inject) for the instance, but other than that you can use `matomo-tracker-js` directly.

**Comment by electrofLy** [comment]
Yes, that is true, but same as the react package in this project, some code can be created so people don't have to do it everytime they want to use the `matomo-tracker-js`.

E.G.:
* Module with which theh instance can be initialized;
* Pipe which you can attach to elements to track events;
* Solution for the page visits in SPA application;

**Comment by electrofLy** [comment]
There has been some updates in the Angular community with some libraries (https://github.com/EmmanuelRoux/ngx-matomoso I will close this issue.
