### ISSUE TITLE
Multiple fake views

### ISSUE THREAD

**Issue by GentillePlume** [Amsterdam/matomo-tracker#54]
Hello there,

I have a little problem. Each time I go on a page, matomo logs 4 times the view. So 4 views on matomo for 1 view in real.
And for on other page it's often 2 times, and other pages no problem. It's depend of the page.

Code of Candidatures page (4 matomo views for 1 real view) : 

```
const MatomoScript = ({renderFoo}) => {
	const {trackPageView} = useMatomo();
	return renderFoo({trackPageView});
};

class Candidatures extends React.Component {
```

```
render() {
		return (
			<Fragment>
				
				<MatomoScript renderFoo={({trackPageView}) => {
					trackPageView();
					return null;
					}
				}
				/>
```

And for login page (2 matomo views for 1 real view) : 

```
const Connexion = ({ history }) => {
	
	const { trackPageView, trackEvent } = useMatomo();
	
	// Track page view
	trackPageView();
```

Index.js
```
const instance = createInstance({
	urlBase: "https://stats.level-up.education/",
	siteId: 2, // optional, default value: `1`
});

ReactDOM.render(
	<MatomoProvider value={instance}>
		<Root/>
	</MatomoProvider>,
	document.getElementById('root')
);
```

**Comment by jonkoops** [comment]
This is because `trackPageView` will be called on every render. Make sure to do it in the right hook or use an effect. For example:

```js
React.useEffect(() => {
  trackPageView()
}, [])
```

For more information see the React docs: https://reactjs.org/docs/hooks-effect.html
