### ISSUE TITLE
Is there any way to globally set a custom dimension value?

### ISSUE THREAD

**Issue by LucusWebsites** [Amsterdam/matomo-tracker#584]
I am using matomo-tracker-react to analyse a react single page app. The app is evolving continuesly and I use a custom dimension to detect what version of the app the user is using.

Currently I do it like this in my main router:

```JS
import {useMatomo} from "@datapunt/matomo-tracker-react";

const Router = () => {
    const {pushInstruction} = useMatomo();

    useEffect(() => {
        pushInstruction('setCustomDimension', 1, process.env.REACT_APP_VERSION);
        // eslint-disable-next-line react-hooks/exhaustive-deps
    }, []);

    ...
```

But I would like to be able to do something like this:

```JS
import { MatomoProvider, createInstance } from "@datapunt/matomo-tracker-react"
const instance = createInstance({
    urlBase: process.env.REACT_APP_MATOMO_URL_BASE,
    siteId: process.env.REACT_APP_MATOMO_SITE_ID,
    customDimensions: [{ // <<<<<< maybe something like this?
        id: 1,
        value: process.env.REACT_APP_VERSION
    }]
});
```

**Comment by chrisvanmook** [comment]
Hi. @LucusWebsites, I'm trying to figure out if this is a specific use-case, where we want to set custom dimensions on initialisation... That would mean we should be consistent and map all tracker object configurations on the initialisation options, that would be hard to maintain. What would be a better idea is perhaps introduce a `initInstructions` field, that we could use like so:
```ts
const instance = createInstance({
    urlBase: process.env.REACT_APP_MATOMO_URL_BASE,
    siteId: process.env.REACT_APP_MATOMO_SITE_ID,
    initInstructions: [{
     name: customDimensions,
     args:  [{
        id: 1,
        value: process.env.REACT_APP_VERSION
    }],
    // other instructions
   }]
});
```

Perhaps this would work for you?

**Comment by LucusWebsites** [comment]
@chrisvanmook Thanks for the quick reply!

And yes that would absolutely work as well!

**Comment by chrisvanmook** [comment]
@LucusWebsites Figured out we could use the `configurations` parameter, please check the pull-request
