### ISSUE TITLE
matomo-react bad idea to call window._paq manually?

### ISSUE THREAD

**Issue by PhilippLiebhart** [Amsterdam/matomo-tracker#761]
Hi all,
i am new to matomo tracking (using the react package) and i was wondering if its bad to call f.e.

window._paq.push(['setUserId', 'USER_ID_HERE']);
instead of
pushInstruction('setUserId', 'USER_ID_HERE');

because when i use pushInstruction('setUserId', 'USER_ID_HERE') it sometimes works and sometimes not..and i don't know why!
.. but if i push it via window._paq.push(['setUserId', 'USER_ID_HERE']) it seems to always work... 

Its because of cookie consent and stuff so i need to set all that later when the user has accepted tracking etc.

so can i mix the package with the normal push methods or would that be a bad idea?

Thank y'all!

**Comment by jonkoops** [comment]
There is no problem with manually pushing instructions to `window._paq`. This library uses simply wraps the existing code from the Matomo client, so any approaches used there are still valid.
