### ISSUE TITLE
Update to support react v18

### ISSUE THREAD

**Issue by Lrigh1** [Amsterdam/matomo-tracker#807]
**Describe the bug**
Missing dependencies for react v18 causing errors

**To Reproduce**
Update to react v18 and try to use this module.

**Additional context**
React v18 has updated, it seems a bot has made multiple requests to solve the dependency updates, but we need an approved maintainer to accept the changes..

**Comment by Etheliene** [comment]
Quickfix for errors regarding missing sourcemaps until this is resolved:

if not present, create `.env` File and insert:

`GENERATE_SOURCEMAP=false`

My error was that sourcemaps were not found.
